### ISSUE TITLE
deepsparse.object_detection.annotate gives prediction not in datasets

### ISSUE THREAD

**Issue by JueXiuHuang** [neuralmagic/deepsparse#957] opened 2023-03-16 13:12 UTC
**Describe the bug**
I trained a model with sparseml and export to onnx format, then I use script below to see the annotation result on an example picture.
`deepsparse.object_detection.annotate --model_filepath ./best_pruned_.onnx --source ./screenshot.png --image_shape 256 256`

And the predictions in result image are not in our datasets.
Below is the result image:
![result-0](https://user-images.githubusercontent.com/32955131/225626508-ad27120a-00bc-47c8-b981-72c6201c68bd.jpg)

Below is dataset.yaml:
[RDRR.txt](https://github.com/neuralmagic/deepsparse/files/10991083/RDRR.txt)

**Environment**
Include all relevant environment information:
1. OS: Ubuntu 20.04
2. Python version: 3.8
3. Package versions:
```
deepsparse==1.4.0
onnx==1.12.0
onnxruntime==1.14.1
sparsezoo==1.4.0
torch==1.12.0
torchvision==0.13.0
```
4. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
```python
>>> import deepsparse.cpu
>>> print(deepsparse.cpu.cpu_architecture())
```

```
{'L1_data_cache_size': 49152, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 1310720, 'L3_cache_size': 18874368, 'architecture': 'x86_64', 'available_cores_per_socket': 6, 'available_num_cores': 6, 'available_num_hw_threads': 12, 'available_num_numa': 1, 'available_num_sockets': 1, 'available_sockets': 1, 'available_threads_per_core': 2, 'bf16': False, 'cores_per_socket': 6, 'dotprod': False, 'i8mm': False, 'isa': 'avx2', 'num_cores': 6, 'num_hw_threads': 12, 'num_numa': 1, 'num_sockets': 1, 'threads_per_core': 2, 'vendor': 'GenuineIntel', 'vendor_id': 'Intel', 'vendor_model': '12th Gen Intel(R) Core(TM) i5-12400F', 'vnni': False}
```

How can I fix this?

**Comment by dbogunowicz** [comment] 2023-03-16 13:23
Oh yes, this absolutely makes sense.

If you take a look inside the `annotation.py` image, you will find that it assumes by default COCO dataset label names:
https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/yolo/annotate.py#L203.

To fix your problem I'd advise you to change L203 such that:

```python

CUSTOM_GAME LABELS = {
    "0": "Assassin",
    "1": "Barrier",
    "2": "Battery",
    "3": "Broken",
...
}
yolo_pipeline = Pipeline.create(
        task="yolo",
        model_path=model_filepath,
        class_names=CUSTOM_GAME LABELS,
        engine_type=engine,
        num_cores=num_cores,
        image_size=model_input_image_shape,
    )
```

**Comment by dbogunowicz** [comment] 2023-03-17 09:11
Judging by the celebrating emoticons attached to my previous message, I guess the issue is resolved :) Closing

**Closed by dbogunowicz** 2023-03-17 09:11 UTC
Labels: bug
