### ISSUE TITLE
Deepsparse in colab

### ISSUE THREAD

**Issue by Vikram12301** [neuralmagic/deepsparse#1031] opened 2023-05-18 04:38 UTC
**Describe the bug**
On running the code from the [documentation](https://docs.neuralmagic.com/use-cases/object-detection/sparsifying) of deepsparse:
```
sparseml.yolov5.train \
  --data VOC.yaml \
  --cfg models_v5.0/yolov5s.yaml \
  --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94?recipe_type=transfer \
  --hyp data/hyps/hyp.finetune.yaml \
  --recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96
```
I got the error:
TypeError: Unable to convert function return value to a Python type! The signature was
() -> handle

**Environment**
I used google colab and installed required libraries with:
```
!pip install deepsparse[server] sparseml[torch,torchvision]
```
and after installation, I had:

torch - Version: 1.12.0
CUDA:
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by dineshchitlangia** [comment] 2023-05-19 05:31
Check the version of numpy installed in your environment.
`pip freeze | grep numpy`

One of the causes of this issue is incompatible numpy version.

**Comment by Vikram12301** [comment] 2023-05-19 08:23
numpy==1.21.6

**Comment by mgoin** [comment] 2023-05-31 16:07
Hi @Vikram12301 this error happens because Tensorboard tries to incorrectly load Tensorflow while we are using PyTorch. Please remove Tensorflow to get past the error: `pip uninstall -y tensorflow`
Here is my colab example: https://colab.research.google.com/drive/1YOhwKCNvQr2GQYx0UcjzfhaaKPUrlJfP?usp=sharing

**Comment by jeanniefinks** [comment] 2023-07-26 17:35
Hello @Vikram12301 
it looks like some time has passed from the advice offered. I am going to go ahead and close this thread. Feel free to re-open to continue the discussion and let us know if you found success or want to continue troubleshooting. We're happy to help.

Jeannie / Neural Magic

**Closed by jeanniefinks** 2023-07-26 17:35 UTC
Labels: bug
