### ISSUE TITLE
yolov8 Task not in tasks !

### ISSUE THREAD

**Issue by MohamedAtef321** [neuralmagic/deepsparse#955] opened 2023-03-16 02:57 UTC
**Describe the bug**
- When I try to annotate image with a yolov8n trained on custom dataset with this code :
``` python
%cd "/content/deepsparse/src/deepsparse/yolov8"

# Annotate image with DeepSparse
!python annotate.py --source "/content/drive/MyDrive/yolov8/5.jpg" \
 --model_filepath "/content/drive/MyDrive/yolov8/bahkar/yolov8_n_t_2_1024p.onnx"
```
- It produces that error :
``` 
/content/deepsparse/src/deepsparse/yolov8
2023-03-16 02:40:23 deepsparse.utils.annotate INFO     Results will be saved to annotation-results/deepsparse-annotations
Traceback (most recent call last):
  File "/content/deepsparse/src/deepsparse/yolov8/annotate.py", line 247, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/content/deepsparse/src/deepsparse/yolov8/annotate.py", line 205, in main
    yolo_pipeline = Pipeline.create(
  File "/usr/local/lib/python3.9/dist-packages/deepsparse/pipeline.py", line 456, in create
    pipeline_constructor = Pipeline._get_task_constructor(task)
  File "/usr/local/lib/python3.9/dist-packages/deepsparse/pipeline.py", line 407, in _get_task_constructor
    SupportedTasks.check_register_task(task, _REGISTERED_PIPELINES.keys())
  File "/usr/local/lib/python3.9/dist-packages/deepsparse/tasks.py", line 183, in check_register_task
    raise ValueError(
ValueError: Unknown Pipeline task yolov8. Currently supported tasks are ['yolo', 'yolact', 'haystack', 'information_retrieval_haystack', 'token_classification', 'glue', 'transformers_embedding_extraction', 'question_answering', 'text_classification', 'open_pif_paf', 'qa', 'sentiment_analysis', 'custom', 'zero_shot_text_classification', 'image_classification', 'ner', 'embedding_extraction']
```

**Expected behavior**
- Not to get that error.

**Environment**
Include all relevant environment information:
- Google Colab with latest updated libraries.

**To Reproduce**
Exact steps to reproduce the behavior:
``` python 
# Install packages for DeepSparse and YOLOv8
!pip install deepsparse[yolo,server]

# ------------------------------------------------------------

%cd /content

# Download example code, model, and sample image
!git clone https://github.com/neuralmagic/deepsparse.git

# ------------------------------------------------------------

%cd "/content/deepsparse/src/deepsparse/yolov8"

# Annotate image with DeepSparse
!python annotate.py --source "/content/drive/MyDrive/yolov8/5.jpg" \
 --model_filepath "/content/drive/MyDrive/yolov8/bahkar/yolov8_n_t_2_1024p.onnx"
```

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by dbogunowicz** [comment] 2023-03-16 10:41
@MohamedAtef321, your issue is at its core a duplicate of https://github.com/neuralmagic/deepsparse/issues/949.
Also note, to install package dependencies for yolov8 you need to run
`pip install deepsparse[yolov8]` instead of `pip install deeepsparse[yolo]`

**Closed by dbogunowicz** 2023-03-16 10:41 UTC
Labels: bug

**Comment by mareksubocz** [comment] 2023-04-15 12:46
I get a message ```WARNING: deepsparse 1.4.2 does not provide the extra 'yolov8' ```
